package com.demo.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-07-19T09:56:23.622+08:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://service.webservice.demo.com/", name = "TestWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface TestWebService {

    @WebMethod
    @RequestWrapper(localName = "show", targetNamespace = "http://service.webservice.demo.com/", className = "com.demo.webservice.service.Show")
    @ResponseWrapper(localName = "showResponse", targetNamespace = "http://service.webservice.demo.com/", className = "com.demo.webservice.service.ShowResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String show(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "login", targetNamespace = "http://service.webservice.demo.com/", className = "com.demo.webservice.service.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://service.webservice.demo.com/", className = "com.demo.webservice.service.LoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String login(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1
    );
}
