
package com.demo.webservice.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-07-19T09:56:23.426+08:00
 * Generated source version: 3.2.5
 *
 */
public final class TestWebService_TestWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.webservice.demo.com/", "TestWebServiceService");

    private TestWebService_TestWebServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = TestWebServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        TestWebServiceService ss = new TestWebServiceService(wsdlURL, SERVICE_NAME);
        com.demo.webservice.service.TestWebService port = ss.getTestWebServicePort();

        {
        System.out.println("Invoking show...");
        String _show_arg0 = "";
        String _show__return = port.show(_show_arg0);
        System.out.println("show.result=" + _show__return);


        }
        {
        System.out.println("Invoking login...");
        String _login_arg0 = "";
        String _login_arg1 = "";
        String _login__return = port.login(_login_arg0, _login_arg1);
        System.out.println("login.result=" + _login__return);


        }

        System.exit(0);
    }

}
