package com.demo.webservice.client;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-07-19T09:56:23.630+08:00
 * Generated source version: 3.2.5
 *
 */
@WebServiceClient(name = "TestWebServiceService",
                  wsdlLocation = "http://localhost:8080/ws/testWeb?wsdl",
                  targetNamespace = "http://service.webservice.demo.com/")
public class TestWebServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.webservice.demo.com/", "TestWebServiceService");
    public final static QName TestWebServicePort = new QName("http://service.webservice.demo.com/", "TestWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ws/testWeb?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TestWebServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ws/testWeb?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TestWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TestWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestWebServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TestWebServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TestWebServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TestWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TestWebService
     */
    @WebEndpoint(name = "TestWebServicePort")
    public com.demo.webservice.service.TestWebService getTestWebServicePort() {
        return super.getPort(TestWebServicePort, com.demo.webservice.service.TestWebService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestWebService
     */
    @WebEndpoint(name = "TestWebServicePort")
    public com.demo.webservice.service.TestWebService getTestWebServicePort(WebServiceFeature... features) {
        return super.getPort(TestWebServicePort, com.demo.webservice.service.TestWebService.class, features);
    }

}
